name: pmp

services:
  pmp_db:
    container_name: pmp_db
    image: postgres:16
    environment:
      POSTGRES_USER: ${PMP_DB_USER}
      POSTGRES_PASSWORD: ${PMP_DB_PASSWORD}
      POSTGRES_DB: ${PMP_DB_NAME}
    ports:
      - "${PMP_DB_HOST_PORT}:5432"
    networks:
      - pmp_net
    volumes:
      - pmp_db_data:/var/lib/postgresql/data

  pmp_api:
    container_name: pmp_api
    image: nginx:alpine
    ports:
      - "${PMP_API_HOST_PORT}:8080"
    networks:
      - pmp_net
    depends_on:
      - pmp_db

networks:
  pmp_net:
    name: pmp_net

volumes:
  pmp_db_data:
    name: pmp_db_data
